# Generated by Django 2.1.5 on 2019-03-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='country',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
