# Generated by Django 2.1.5 on 2019-04-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_hit_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('subheader', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('startedAt', models.CharField(max_length=100)),
                ('endedAt', models.CharField(max_length=100)),
            ],
        ),
    ]
