# Generated by Django 2.1.5 on 2019-04-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190402_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='subheader',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
