# Generated by Django 2.1.5 on 2019-04-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_about_education_interests_plandtechs_workflow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interests',
            new_name='Interest',
        ),
        migrations.RenameModel(
            old_name='PlAndTechs',
            new_name='PlAndTech',
        ),
    ]
